import path from 'path';
import { defineConfig } from 'vite';
import { readdirSync, existsSync } from 'fs';
import { NON_PRODUCTION_HTML_FILES } from './config/indexing-rules.js';
import { seoFoundationPlugin } from './seo/vite-plugin.js';

const MODULE_SHARED_SCRIPTS = new Set([
  'nav.js',
  'utils.js',
  'index.js',
  'reveal.js',
  'magnetic.js',
  'split-text.js',
  'card-effects.js',
  'reactive-effects.js',
  'cro.js',
  'case-study-proofs.js',
]);

const moduleScriptTagsPlugin = () => ({
  name: 'module-script-tags',
  transformIndexHtml: {
    order: 'pre' as const,
    handler(html: string) {
      return html.replace(
        /<script\b([^>]*?)\bsrc=(["'])([^"']+)\2([^>]*)><\/script>/gi,
        (match, before, quote, src, after) => {
          const normalizedSrc = String(src || '').replace(/^\.\//, '').replace(/^\//, '');
          const basename = path.posix.basename(normalizedSrc);

          if (!MODULE_SHARED_SCRIPTS.has(basename)) {
            return match;
          }

          const attrs = `${before} src=${quote}${src}${quote}${after}`;
          if (/\btype\s*=\s*["']module["']/i.test(attrs)) {
            return match;
          }

          const cleanedAttrs = attrs.replace(/\sdefer\b/gi, '');
          return `<script type="module"${cleanedAttrs}></script>`;
        },
      );
    },
  },
});

// Get all HTML files for multi-page app build
const getHtmlEntries = () => {
  const entries: Record<string, string> = {};

  // Root HTML files
  const htmlFiles = readdirSync('.').filter(
    f =>
      f.endsWith('.html') &&
      !f.includes('backup') &&
      !NON_PRODUCTION_HTML_FILES.includes(f),
  );
  htmlFiles.forEach(file => {
    const name = file.replace('.html', '');
    entries[name] = path.resolve(__dirname, file);
  });

  // Admin folder
  if (existsSync('./admin/index.html')) {
    entries['admin/index'] = path.resolve(__dirname, 'admin/index.html');
  }

  // Blog posts (generated by build:blog script)
  if (existsSync('./blog')) {
    const blogFiles = readdirSync('./blog').filter(f => f.endsWith('.html'));
    blogFiles.forEach(file => {
      const name = file.replace('.html', '');
      entries[`blog/${name}`] = path.resolve(__dirname, 'blog', file);
    });
  }

  // Case studies (generated by build:case-studies script)
  if (existsSync('./case-studies')) {
    const caseStudyFiles = readdirSync('./case-studies').filter(f => f.endsWith('.html'));
    caseStudyFiles.forEach(file => {
      const name = file.replace('.html', '');
      entries[`case-studies/${name}`] = path.resolve(__dirname, 'case-studies', file);
    });
  }

  return entries;
};

export default defineConfig(() => {
    return {
      server: {
        port: 3000,
        host: '0.0.0.0',
      },
      plugins: [moduleScriptTagsPlugin(), seoFoundationPlugin()],
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '.'),
        }
      },
      build: {
        // Multi-page app support
        rollupOptions: {
          input: getHtmlEntries(),
          output: {
            // Chunk naming for better caching
            chunkFileNames: 'assets/js/[name]-[hash].js',
            entryFileNames: 'assets/js/[name]-[hash].js',
            assetFileNames: (assetInfo) => {
              const ext = assetInfo.name?.split('.').pop() || '';
              if (/png|jpe?g|svg|gif|webp|avif/i.test(ext)) {
                return 'assets/images/[name]-[hash][extname]';
              }
              if (/css/i.test(ext)) {
                return 'assets/css/[name]-[hash][extname]';
              }
              return 'assets/[name]-[hash][extname]';
            },
          },
        },
        // Minification
        minify: 'terser',
        terserOptions: {
          compress: {
            drop_console: true,
            drop_debugger: true,
          },
        },
        // CSS optimization
        cssMinify: true,
        // Source maps for debugging (optional, disable for smaller builds)
        sourcemap: false,
        // Output directory
        outDir: 'dist',
        // Clean output directory before build
        emptyOutDir: true,
      },
    };
});
